/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdResultsRouteImport } from './routes/jobs/$jobId/results'
import { Route as JobsJobIdProcessingRouteImport } from './routes/jobs/$jobId/processing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdResultsRoute = JobsJobIdResultsRouteImport.update({
  id: '/jobs/$jobId/results',
  path: '/jobs/$jobId/results',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdProcessingRoute = JobsJobIdProcessingRouteImport.update({
  id: '/jobs/$jobId/processing',
  path: '/jobs/$jobId/processing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs/$jobId/processing': typeof JobsJobIdProcessingRoute
  '/jobs/$jobId/results': typeof JobsJobIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs/$jobId/processing': typeof JobsJobIdProcessingRoute
  '/jobs/$jobId/results': typeof JobsJobIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs/$jobId/processing': typeof JobsJobIdProcessingRoute
  '/jobs/$jobId/results': typeof JobsJobIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jobs/$jobId/processing' | '/jobs/$jobId/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jobs/$jobId/processing' | '/jobs/$jobId/results'
  id: '__root__' | '/' | '/jobs/$jobId/processing' | '/jobs/$jobId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsJobIdProcessingRoute: typeof JobsJobIdProcessingRoute
  JobsJobIdResultsRoute: typeof JobsJobIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/results': {
      id: '/jobs/$jobId/results'
      path: '/jobs/$jobId/results'
      fullPath: '/jobs/$jobId/results'
      preLoaderRoute: typeof JobsJobIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/processing': {
      id: '/jobs/$jobId/processing'
      path: '/jobs/$jobId/processing'
      fullPath: '/jobs/$jobId/processing'
      preLoaderRoute: typeof JobsJobIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsJobIdProcessingRoute: JobsJobIdProcessingRoute,
  JobsJobIdResultsRoute: JobsJobIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
