ssl_certificate     /etc/letsencrypt/live/clipper.moni.id/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/clipper.moni.id/privkey.pem;
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_ciphers         HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;
ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 10m;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
